# Channel data columns
columns = [
    "ID", "Channel Name", "Telegram URL", 
    "Credibility Score", "Credibility Category", 
    "Relevance Score", "Relevance Category", 
    "Engagement Score", "Engagement Category", 
    "Posting Frequency Score", "Frequency Category", 
    "Subscriber Count Score", "Audience Category"
]

# List of channels with their metadata
channels = [
    [1, "Cyber Security News", "https://t.me/cyber_security_channel", 9, "High", 10, "Very High", 6, "Moderate", 9, "Frequent", 9, "Large"],
    [2, "Cyber Security – InfoSec/IT Security Experts (Group)", "https://t.me/cybersecurityexperts", 8, "High", 9, "High", 8, "High", 8, "Frequent", 9, "Large"],
    [3, "Cloud & Cybersecurity", "https://t.me/cloudandcybersecurity", 8, "High", 8, "High", 7, "Moderate", 8, "Frequent", 8, "Large"],
    [4, "Cybersecurity & Privacy News", "https://t.me/cibsecurity", 9, "High", 9, "High", 5, "Medium", 9, "Frequent", 8, "Large"],
    [5, "Android Security & Malware", "https://t.me/androidMalware", 8, "High", 8, "High", 7, "Moderate", 8, "Frequent", 9, "Large"],
    [6, "Malware Research (Group)", "https://t.me/MalwareResearch", 9, "High", 9, "High", 8, "High", 7, "Regular", 7, "Medium"],
    [7, "BugCrowd (Bug Bounty Group)", "https://t.me/BugCrowd", 8, "High", 8, "High", 8, "High", 8, "Frequent", 8, "Large"],
    [8, "Red Team Alerts", "https://t.me/redteamalerts", 7, "High", 9, "Very High", 6, "Moderate", 9, "Frequent", 8, "Large"],
    [9, "Blue Team Alerts", "https://t.me/blueteamalerts", 7, "High", 9, "Very High", 6, "Moderate", 9, "Frequent", 7, "Medium"],
    [10, "IT Security Alerts", "https://t.me/itsecalert", 8, "High", 9, "High", 6, "Moderate", 9, "Frequent", 8, "Large"],
    [13, "CVE Notify", "https://t.me/cveNotify", 9, "High", 10, "Very High", 5, "Medium", 10, "Very Frequent", 8, "Large"],
    [14, "Malware News (malwr)", "https://t.me/malwr", 7, "Fair", 9, "High", 5, "Medium", 8, "Frequent", 8, "Large"],
    [15, "BleepingComputer News", "https://t.me/bleepingcomputer", 9, "High", 8, "High", 5, "Medium", 8, "Frequent", 7, "Medium"],
    [16, "The Hacker News (THN)", "https://t.me/thehackernews", 9, "High", 9, "High", 6, "Moderate", 9, "Frequent", 10, "Very Large"],
    [17, "Cyber Threat Intelligence (CTI Now)", "https://t.me/ctinow", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [18, "Learn Cybersecurity (TeamMatrix)", "https://t.me/teammatrixs", 7, "Good", 7, "High", 6, "Moderate", 7, "Regular", 6, "Medium"],
    [19, "Dark Web Informer (CTI)", "https://t.me/TheDarkWebInformer", 8, "High", 8, "High", 5, "Medium", 7, "Regular", 6, "Medium"],
    [20, "Hacker Exploits", "https://t.me/hackerexploits", 6, "Fair", 7, "High", 5, "Medium", 6, "Regular", 5, "Small"],
    [21, "Infosec Tutorials (Jazer)", "https://t.me/cybersecuriti", 6, "Fair", 6, "Moderate", 5, "Medium", 7, "Regular", 6, "Medium"],
    [22, "Cyber Ninja Sec Community", "https://t.me/Cyb3rn1nj4", 6, "Fair", 7, "High", 5, "Medium", 7, "Regular", 6, "Medium"],
    [23, "HackerSploit Channel", "https://t.me/Hackersploit", 8, "High", 6, "Moderate", 4, "Low", 5, "Low", 3, "Very Small"],
    [24, "Security Awareness", "https://t.me/SecurityAwareness", 7, "Good", 7, "High", 5, "Medium", 6, "Regular", 6, "Medium"],
    [25, "OSINT & Threats", "https://t.me/OSINT_threats", 7, "Good", 8, "High", 5, "Medium", 6, "Regular", 5, "Small"],
    [26, "Exploit Development", "https://t.me/ExploitDev", 7, "Good", 8, "High", 5, "Medium", 6, "Regular", 5, "Small"],
    [27, "Ransomware Alerts", "https://t.me/RansomwareAlerts", 8, "High", 9, "High", 5, "Medium", 7, "Regular", 6, "Medium"],
    [28, "Vuln Digest", "https://t.me/VulnDigest", 8, "High", 9, "High", 5, "Medium", 8, "Frequent", 6, "Medium"],
    [29, "Data Breach News", "https://t.me/DataBreachNews", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [30, "Threat Intel Updates", "https://t.me/ThreatIntel", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [31, "CyberSec Jobs & Alerts", "https://t.me/CyberSecurityJobs", 7, "Good", 6, "Moderate", 5, "Medium", 7, "Regular", 6, "Medium"],
    [32, "Threat Hunting & DFIR", "https://t.me/DFIRchat", 7, "Good", 8, "High", 6, "Moderate", 6, "Regular", 5, "Small"],
    [33, "Exploit News", "https://t.me/Exploit_News", 7, "Good", 9, "High", 5, "Medium", 7, "Regular", 6, "Medium"],
    [34, "Vulnerability Alert", "https://t.me/VulnerabilityAlert", 8, "High", 10, "Very High", 5, "Medium", 9, "Frequent", 7, "Medium"],
    [35, "Cybersecurity Magazine", "https://t.me/CyberSecMagazine", 7, "Good", 7, "High", 5, "Medium", 6, "Regular", 6, "Medium"],
    [36, "Hacker News Feed", "https://t.me/HNsecurity", 6, "Fair", 6, "Moderate", 4, "Low", 9, "Frequent", 6, "Medium"],
    [37, "Security Tool Updates", "https://t.me/SecTools", 7, "Good", 8, "High", 5, "Medium", 8, "Frequent", 6, "Medium"],
    [38, "Zero-Day Channel", "https://t.me/ZeroDayAlerts", 8, "High", 10, "Very High", 5, "Medium", 8, "Frequent", 6, "Medium"],
    [39, "Malware Analysis Hub", "https://t.me/MalwareAnalysisHub", 8, "High", 9, "High", 6, "Moderate", 7, "Regular", 6, "Medium"],
    [40, "SOC Threat Feeds", "https://t.me/SOCThreatFeeds", 7, "Good", 8, "High", 5, "Medium", 8, "Frequent", 5, "Small"],
    [41, "CyberSec Reddit Feed", "https://t.me/RedditCyberSec", 6, "Fair", 7, "High", 4, "Low", 9, "Frequent", 5, "Small"],
    [42, "Hackers Archive", "https://t.me/HackersArchive", 6, "Fair", 6, "Moderate", 4, "Low", 6, "Regular", 5, "Small"],
    [43, "Security Breach Monitor", "https://t.me/SecBreachMonitor", 7, "Good", 9, "High", 5, "Medium", 7, "Regular", 5, "Small"],
    [44, "Cyber Intelligence Wire", "https://t.me/CyberIntelWire", 7, "Good", 8, "High", 5, "Medium", 7, "Regular", 5, "Small"],
    [45, "Vulnerabilities Feed", "https://t.me/VulnerabilityFeed", 8, "High", 10, "Very High", 4, "Low", 10, "Very Frequent", 5, "Small"],
    [46, "Exploit Database Updates", "https://t.me/ExploitDB", 8, "High", 9, "High", 4, "Low", 9, "Frequent", 5, "Small"],
    [47, "INFOSEC Community", "https://t.me/InfoSecCommunity", 7, "Good", 7, "High", 6, "Moderate", 6, "Regular", 6, "Medium"],
    [48, "Threat Research Updates", "https://t.me/ThreatResearch", 8, "High", 8, "High", 5, "Medium", 6, "Regular", 5, "Small"],
    [49, "CyberSec Insights", "https://t.me/CyberSecInsights", 7, "Good", 8, "High", 5, "Medium", 6, "Regular", 5, "Small"],
    [50, "SOC Prime Threat Bounty", "https://t.me/SocPrimeThreat", 7, "Good", 8, "High", 5, "Medium", 5, "Low", 5, "Small"],

    # Channels from deepdarkCTI (Status: Valid/Online, High Credibility)
    [51, "Ares Private Channel", "https://t.me/+9ETFYLy5Tc1lNzBh", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [52, "Goblin's Database", "https://t.me/+9P5FQ85afTc4NGNl", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [53, "AiDLocker Group", "https://t.me/aidlock", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [54, "Anonymous Russia", "https://t.me/anon_by", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [55, "Anon Sec", "https://t.me/anon_sec_Official", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [56, "Anonymous South Africa", "https://t.me/anonymous_south_africa", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [57, "APT Iran", "https://t.me/APTIRAN", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [58, "Atlantis CyberArmy", "https://t.me/atlantiscyberarmy", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [59, "Against The West", "https://t.me/atw2022", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [60, "Bl00dy Ransomware Gang", "https://t.me/bl00dy_Ransomware_Gang", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [61, "BlackVault", "https://t.me/blackvaultcc", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [62, "Breach Detector", "https://t.me/breachdetector", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [63, "CyberCat Channel", "https://t.me/CyberCatHack", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [64, "Cyber Court", "https://t.me/cybercourt_io", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [65, "Database Market", "https://t.me/databasemarkett", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [66, "DragonForce Malaysia", "https://t.me/dragonforceio", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [67, "Dumped Forum", "https://t.me/DumpedOfficial", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [68, "8BASE", "https://t.me/eightbase", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [69, "GhostSec Service", "https://t.me/GhostSecS", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [70, "Homeland Justice", "https://t.me/justice_homeland", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [71, "Killnet DDoS", "https://t.me/KILLNETddos", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [72, "Killnet Mirror", "https://t.me/killnet_mirror", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [73, "LockBit APT", "https://t.me/LockBit_APT", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [74, "Lulzsec Muslims", "https://t.me/lulzsecmuslimsworld", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [75, "Marketo Leaks", "https://t.me/marketo_leaks", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [76, "Metastealer Official", "https://t.me/metastealer_official", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [77, "Milad Leaks", "https://t.me/MiladLeaks", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [78, "Naos Base", "https://t.me/naosbase", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [79, "NetHunt3r", "https://t.me/NetHunt3r", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [80, "Net Ghost Security", "https://t.me/NetGhostSecurity", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [81, "Liquid Blood", "https://t.me/Liquid_Blood", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [82, "Exodus Market", "https://t.me/exodusmarketchannel", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [83, "Breach Watchers", "https://t.me/breachwatchers", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [84, "The Moskovski Times", "https://t.me/TheMoskovskiTimes", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [85, "RADNET64", "https://t.me/radnetbak", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [86, "Dragon Ransom", "https://t.me/DragonRansom", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [87, "Aligator Black Hat", "https://t.me/OPRATIONSALIGATOR", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [88, "INDOHAXSEC", "https://t.me/INDOHAXSEC", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [89, "Danger Zone Forum", "https://t.me/DangerZoneForum", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [90, "Filehaus", "https://t.me/filehaus", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [91, "Esteem Restoration Eagle", "https://t.me/esteemrestorationeagle", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [92, "Bratva", "https://t.me/bratvacorp", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [93, "Cyber Battle", "https://t.me/CyperBattle", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [94, "Alixsec English", "https://t.me/alixsecenglish", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [95, "Anonymous Italia Chat", "https://t.me/AnonSecItaChat", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [96, "Anonymous Italia Channel", "https://t.me/AnonSecITA", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [97, "Spider-X", "https://t.me/SpidrXXX", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [98, "Laneh Dark", "https://t.me/Laneh_dark", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [99, "Laneh News", "https://t.me/Laneh_news", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [100, "Legion Service News", "https://t.me/LegionServiceNews", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [101, "Team K70", "https://t.me/hackrsk70", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [102, "Crazy Hunters Team", "https://t.me/CrazyHuntersTeam", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [103, "Codebreakers", "https://t.me/ircodebreakers", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [104, "AgencyInt Marketplace", "https://t.me/agencyInt", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [105, "MadCap", "https://t.me/MadCapZone", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [106, "Satanlock", "https://t.me/Satanlock", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [107, "MLCloud Hosting News", "https://t.me/mlcloud_hosting_news", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [108, "Cyber Threat Intelligence Feeds", "https://t.me/ctifeeds", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [109, "CVE Feed", "https://t.me/cveNotify", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [110, "Cyber Detective", "https://t.me/cybdetective", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [111, "Cyber Av3ngers", "https://t.me/CyberAv3ngers", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [112, "Darkfeed News", "https://t.me/DarkfeedNews", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [113, "Dark Forums", "https://t.me/DarkForums", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [114, "Data Leak Home", "https://t.me/DataLeakHome", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [115, "DDoS Services", "https://t.me/ddossatmak", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [116, "DDoS Separ", "https://t.me/ddos_separ", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [117, "BlackObServers Channel", "https://t.me/ddostm1", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [118, "Eternity Malware", "https://t.me/EternityMalwareTeam", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [119, "Exploit Service", "https://t.me/ExploitService", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [120, "Freshtools Market", "https://t.me/freshtoolsnet", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [121, "Git Tools", "https://t.me/GitTools", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [122, "GladDOS Official", "https://t.me/gladdos69_official", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [123, "Goblins Gang", "https://t.me/goblins_gang", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [124, "Goblins Hub", "https://t.me/goblins_hub", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [125, "GoneTeam", "https://t.me/GoneTeam410", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [126, "Gonjeshke Darande", "https://t.me/GonjeshkeDarand", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [127, "Grand Give", "https://t.me/grandgive", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [128, "Gulf Docs", "https://t.me/gulfdocs", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [129, "Beregini", "https://t.me/hackberegini", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [130, "Hack Tricks", "https://t.me/hacker_trick", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [131, "Offensive Security", "https://t.me/hackgit", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [132, "HackNeT", "https://t.me/hack_n3t", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [133, "Hadesh0p", "https://t.me/hadesh0p", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [134, "HiveNET", "https://t.me/HiveNETT", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [135, "HK4GANG", "https://t.me/HK4GANG", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [136, "Hooshyaran-e Vatan", "https://t.me/hooshyarane", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [137, "Horus Forum", "https://t.me/HorusForumRus", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [138, "Horus Evolution Reserve", "https://t.me/horus_reservs", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [139, "Horus Evolution", "https://t.me/horusteam_officiall", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [140, "HQ Cracking", "https://t.me/HQCracking", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [141, "HQPROX", "https://t.me/HQPROX", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [142, "Hudy Stock", "https://t.me/hudyhstock", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [143, "ICrew Hackers", "https://t.me/icrewhackers", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [144, "Illicit Service Chat", "https://t.me/illsvcchat", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [145, "Illicit Service Upload", "https://t.me/illsvcleaksupload", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [146, "Illicit Service", "https://t.me/illsvc", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [147, "Indian Cyber Force", "https://t.me/INDIAN_CYBER_FORCE", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [148, "Industrial Spy", "https://t.me/Industrial_Spy", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [149, "Infinity Hackers By", "https://t.me/infinity_hackers_group", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [150, "Infinity Forum", "https://t.me/INFINITY_HACKERSS", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [151, "Inj3ct0rs", "https://t.me/inj3ct0rs", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [152, "IT Army of Ukraine", "https://t.me/itarmyofukraine2022", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [153, "IT Security Alerts", "https://t.me/itsecalert", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [154, "Jester Stealer", "https://t.me/jester_stealer_channel", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [155, "Joker Reborn", "https://t.me/joker_reborn", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [156, "TEAM1910", "https://t.me/jokmajd", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [157, "Karakurt", "https://t.me/karakurt_news", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [158, "DARKNET", "https://t.me/killmilk_rus", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [159, "KillnetLATAM Chat", "https://t.me/KillnetChatLATAM", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [160, "KittenSec", "https://t.me/kittensec", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [161, "Latest Bin", "https://t.me/latestbin", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [162, "Latest Leaks", "https://t.me/latest_leaks", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [163, "Lazarus Channel", "https://t.me/lazarus_apt18", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [164, "23andme Leak Database", "https://t.me/Leak_23andme", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [165, "Data Leaks Private", "https://t.me/leakdataprivate", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [166, "d3ltaboys Group 1", "https://t.me/leak_db1", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [167, "d3ltaboys Group 2", "https://t.me/leak_db2", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [168, "d3ltaboys Group 3", "https://t.me/leak_db3", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [169, "Leaks & Breaches", "https://t.me/Leaked_BreachDBS", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [170, "Database of Data Breaches", "https://t.me/Leaked_Breached_Hacked_Database", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [171, "Leaked Databases", "https://t.me/leaked_databases", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [172, "Leaked Database", "https://t.me/leaked_detabase", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [173, "LeaksData", "https://t.me/LeaksData", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [174, "Leaks Marts", "https://t.me/leaksmarts", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [175, "Learn Exploit", "https://t.me/LeaRNEXploIT", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [176, "General Hacking Tutorials", "https://t.me/LearnExploit", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [177, "Le Fou Samples", "https://t.me/lefousamples", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [178, "Legion Service News Group", "https://t.me/LegionServiceNewsGroup", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [179, "Logs Gang 2", "https://t.me/logsgang2", 8, "High", 9, "High", 6, "Moderate", 8, "Frequent", 7, "Medium"],
    [180, "Lulzsec Muslims World", "https://t.me/lulzsecmuslimsworld", 8, "High", 10, "Very High", 6, "Moderate", 8, "Frequent", 7, "Medium"]
] 